/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ec.vista;

import ec.edu.ec.modelo.Juego;
import ec.edu.ec.modelo.Laberitno;
import ec.edu.ec.modelo.Personaje;
import ec.edu.ec.vista.mensajes.Ayuda;
import java.applet.AudioClip;
import java.awt.Graphics;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Erick
 */
public class LaberintoGUI extends javax.swing.JFrame {

    Laberitno laberinto;
    Personaje personaje;
    LaberintoGUI l;
    JuegoPerdido j;
    static Juego juego;
    private static boolean bandera = true;

    /**
     * Creates new form LaberintoGUI
     */
    public LaberintoGUI() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/lab.png")).getImage());
        setLocationRelativeTo(null);
        laberinto = new Laberitno(Ventana1.tamanoLaberitno);
        personaje = new Personaje();

        int tamanoTotal = Laberitno.tamano * Laberitno.esteLaberinto.length;
        setSize(tamanoTotal, tamanoTotal);
        setFocusable(true);
        game();


//        if (bandera) { //Se vuelve a generar otro laberinto sin esta condicion
//            bandera = false;
//        }
//        else {
//            bandera = false;
//            game();
//        }
    }
    
    public void fin() {
        this.setEnabled(false);
        this.dispose();
        new JuegoGanado().setVisible(true);
    }

    private void fin1() {
        this.dispose();
        new JuegoPerdido().setVisible(true);
        this.setEnabled(false);
    }

    public void game() {
        this.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                personaje.teclaPresionada(e);
                if (Character.toLowerCase(e.getKeyChar()) == 'y') {
                    
                    fin1();
                    
                } else if (Personaje.fin) {
                    Personaje.fin = false;
                    fin();
                }
                repaint();
            }
        });

    }

    public void paint(Graphics g) {
        laberinto.pintarLaberinto(g);
        personaje.pintarPersonaje(g);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laberinto @ERA");
        setUndecorated(true);

        jMenuBar1.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Ayuda");
        jMenu1.setToolTipText("Información y consejos");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
         new Ayuda(this, true).setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaberintoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaberintoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaberintoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaberintoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new LaberintoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
