/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ec.vista;

import ec.edu.ec.control.BackTracking;
import ec.edu.ec.control.Coordenada;
import ec.edu.ec.control.Maze;
import ec.edu.ec.modelo.Laberitno;
import static ec.edu.ec.modelo.Laberitno.esteLaberinto;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.List;

/**
 *
 * @author Erick
 */
public class Solucion extends javax.swing.JInternalFrame {

    Laberitno lab;
    /**
     * Creates new form Solucion
     */
    public Solucion() {
        initComponents();
        lab = new Laberitno();
        lab.verSolucion();
        Laberitno.tamano = 558 / Laberitno.esteLaberinto.length;
    }

    @Override
    public void paint(Graphics g) {
        lab.pintarLaberinto(g);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
